### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by juliannabaker** [jlb2886/news-app#1]
Clone Repository
Run Project on Android
Understand Code Base

**Comment by Robster45** [comment]
So for some reason all of the code is giving me massive errors. I think it has something to do with the Prettier extension, got any ideas on what I can do to fix this?

**Comment by jlb2886** [comment]
Want to meet through zoom sometime this week and I can go through it with you. You probably have to install some things on your computer. It shouldn't be the prettier extension but I can always check that out. For the time being do you want to send me some screen shots of the errors?

**Comment by juliannabaker** [comment]
Want to meet through zoom sometime this week and I can go through it with you. You probably have to install some things on your computer. For the time being, do you want to send me some screen shots of the errors?

**Comment by Robster45** [comment]
[image: image.png]
That is the error that shows up each time. I've tried looking it up but
most spots say that the Fix should work, and if it doesn't, I need to
install new things into the project which I would like to avoid since it's
a repo etc. But yeah, if we can set up a zoom, that might be helpful.

Thanks,
Robley
